<a href="https://colab.research.google.com/github/Alagammaipl/twitter-data-scrapping/blob/main/Twitter_data_scraping_using_snscrape_and_streamlit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***installation of snscrape library***

In [1]:
!pip3 install snscrape

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: snscrape in /usr/local/lib/python3.8/dist-packages (0.5.0.20230113)
Requirement already satisfied: filelock in /usr/local/lib/python3.8/dist-packages (from snscrape) (3.9.0)
Requirement already satisfied: pytz in /usr/local/lib/python3.8/dist-packages (from snscrape) (2022.7)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.8/dist-packages (from snscrape) (2.25.1)
Requirement already satisfied: lxml in /usr/local/lib/python3.8/dist-packages (from snscrape) (4.9.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.8/dist-packages (from snscrape) (4.6.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (1.24.3)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (1.7.1)

***scraping tweets***

In [32]:
!snscrape --jsonl --progress --max-results 1000 twitter-search adhani > user-tweets.json

Scraping, 100 results so far
Scraping, 200 results so far
Scraping, 300 results so far
Scraping, 400 results so far
Scraping, 500 results so far
Scraping, 600 results so far
Scraping, 700 results so far
Scraping, 800 results so far
Scraping, 900 results so far
Scraping, 1000 results so far
Stopped scraping after 1000 results due to --max-results

***converting to dataframe***

In [24]:
import pandas as pd
df = pd.read_json("/content/user-tweets.json",  lines=True)
df.head(5)

,_type,url,date,rawContent,renderedContent,id,user,replyCount,retweetCount,likeCount,...,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags,card,viewCount,vibe
0,snscrape.modules.twitter.Tweet,https://twitter.com/AakunuriSuresh/status/1620...,2023-02-01 10:35:36+00:00,@ysathishreddy @KTRBRS @prakashraaj @drgaganbh...,@ysathishreddy @KTRBRS @prakashraaj @drgaganbh...,1620732594320207872,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,1.620722e+18,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",None,None,None,NaN,None,14.0,NaN
1,snscrape.modules.twitter.Tweet,https://twitter.com/SevadalNLG/status/16207316...,2023-02-01 10:31:42+00:00,Where is Asia's richest person!\n#Adhani https...,Where is Asia's richest person!\n#Adhani https...,1620731611443761152,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,1,0,...,NaN,None,None,None,None,[Adhani],NaN,None,11.0,NaN
2,snscrape.modules.twitter.Tweet,https://twitter.com/harishstarc/status/1620708...,2023-02-01 09:00:49+00:00,Budget 2023 \n\nInda Budget mulamaa indiaya Po...,Budget 2023 \n\nInda Budget mulamaa indiaya Po...,1620708738750623745,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,NaN,None,None,None,None,None,NaN,None,8.0,NaN
3,snscrape.modules.twitter.Tweet,https://twitter.com/MADGURISrinvas/status/1620...,2023-02-01 08:12:14+00:00,@SujathaGoud6 Telangana la mapia lu paripalana...,@SujathaGoud6 Telangana la mapia lu paripalana...,1620696513134620672,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,1.620473e+18,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",None,None,None,NaN,None,11.0,NaN
4,snscrape.modules.twitter.Tweet,https://twitter.com/ICEBOYBILL/status/16206921...,2023-02-01 07:54:59+00:00,@pushpendrakum why we still listen to this Bul...,@pushpendrakum why we still listen to this Bul...,1620692173737046017,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,1.620671e+18,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",None,None,"[Budget2023, Adhani]",NaN,None,63.0,NaN

**droping and modifications in df**

In [25]:
df['date'] = pd.to_datetime(df['date']).dt.date
df

,_type,url,date,rawContent,renderedContent,id,user,replyCount,retweetCount,likeCount,...,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags,card,viewCount,vibe
0,snscrape.modules.twitter.Tweet,https://twitter.com/AakunuriSuresh/status/1620...,2023-02-01,@ysathishreddy @KTRBRS @prakashraaj @drgaganbh...,@ysathishreddy @KTRBRS @prakashraaj @drgaganbh...,1620732594320207872,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,1.620722e+18,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",None,None,None,NaN,None,14.0,NaN
1,snscrape.modules.twitter.Tweet,https://twitter.com/SevadalNLG/status/16207316...,2023-02-01,Where is Asia's richest person!\n#Adhani https...,Where is Asia's richest person!\n#Adhani https...,1620731611443761152,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,1,0,...,NaN,None,None,None,None,[Adhani],NaN,None,11.0,NaN
2,snscrape.modules.twitter.Tweet,https://twitter.com/harishstarc/status/1620708...,2023-02-01,Budget 2023 \n\nInda Budget mulamaa indiaya Po...,Budget 2023 \n\nInda Budget mulamaa indiaya Po...,1620708738750623745,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,NaN,None,None,None,None,None,NaN,None,8.0,NaN
3,snscrape.modules.twitter.Tweet,https://twitter.com/MADGURISrinvas/status/1620...,2023-02-01,@SujathaGoud6 Telangana la mapia lu paripalana...,@SujathaGoud6 Telangana la mapia lu paripalana...,1620696513134620672,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,1.620473e+18,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",None,None,None,NaN,None,11.0,NaN
4,snscrape.modules.twitter.Tweet,https://twitter.com/ICEBOYBILL/status/16206921...,2023-02-01,@pushpendrakum why we still listen to this Bul...,@pushpendrakum why we still listen to this Bul...,1620692173737046017,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,1.620671e+18,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",None,None,"[Budget2023, Adhani]",NaN,None,63.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,snscrape.modules.twitter.Tweet,https://twitter.com/Breany_22/status/160038885...,2022-12-07,Nimerelate na hiyi story ya Josh.Mamangu ashai...,Nimerelate na hiyi story ya Josh.Mamangu ashai...,1600388852148903936,"{'_type': 'snscrape.modules.twitter.User', 'us...",3,7,49,...,NaN,None,None,None,None,None,NaN,None,NaN,NaN
996,snscrape.modules.twitter.Tweet,https://twitter.com/AntiIndian4BJP/status/1600...,2022-12-07,புதிரா இந்தியா என்ற பெயரில் அதானி இந்தியா: 205...,புதிரா இந்தியா என்ற பெயரில் அதானி இந்தியா: 205...,1600387901623525376,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,NaN,None,None,None,None,"[modi, karnataka, farmer, Onion, price, adhani]",NaN,{'_type': 'snscrape.modules.twitter.SummaryCar...,NaN,NaN
997,snscrape.modules.twitter.Tweet,https://twitter.com/_siqaman_/status/160038199...,2022-12-07,@Macha_Icon Bro chunga asisahau akikupea bj ad...,@Macha_Icon Bro chunga asisahau akikupea bj ad...,1600381994260525056,"{'_type': 'snscrape.modules.twitter.User', 'us...",1,1,2,...,1.600378e+18,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",None,None,None,NaN,None,NaN,NaN
998,snscrape.modules.twitter.Tweet,https://twitter.com/RamanaFrom/status/16003764...,2022-12-07,@Siri4BRS Modhi desha drohi. Ramudu peru chepp...,@Siri4BRS Modhi desha drohi. Ramudu peru chepp...,1600376424019681280,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,1,...,1.599988e+18,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",None,None,None,NaN,None,NaN,NaN
999,snscrape.modules.twitter.Tweet,https://twitter.com/SeChell6/status/1600362066...,2022-12-07,Adhani Businesses \nalready in Eelam &amp; Sri...,Adhani Businesses \nalready in Eelam &amp; Sri...,1600362066866450432,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,1,...,NaN,None,None,None,None,None,NaN,None,NaN,NaN

In [26]:
df1 = df.drop(['_type', 'conversationId','sourceUrl','links','media','rawContent','quoteCount', 'inReplyToTweetId','inReplyToUser','mentionedUsers','coordinates', 'retweetedTweet', 'quotedTweet','sourceLabel','place',	'hashtags',	'cashtags',	'card','viewCount', 'vibe'], axis = 1)
df1.head()

,url,date,renderedContent,id,user,replyCount,retweetCount,likeCount,lang,source
0,https://twitter.com/AakunuriSuresh/status/1620...,2023-02-01,@ysathishreddy @KTRBRS @prakashraaj @drgaganbh...,1620732594320207872,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,en,"<a href=""http://twitter.com/download/android"" ..."
1,https://twitter.com/SevadalNLG/status/16207316...,2023-02-01,Where is Asia's richest person!\n#Adhani https...,1620731611443761152,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,1,0,en,"<a href=""http://twitter.com/download/android"" ..."
2,https://twitter.com/harishstarc/status/1620708...,2023-02-01,Budget 2023 \n\nInda Budget mulamaa indiaya Po...,1620708738750623745,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,in,"<a href=""http://twitter.com/download/android"" ..."
3,https://twitter.com/MADGURISrinvas/status/1620...,2023-02-01,@SujathaGoud6 Telangana la mapia lu paripalana...,1620696513134620672,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,et,"<a href=""http://twitter.com/download/android"" ..."
4,https://twitter.com/ICEBOYBILL/status/16206921...,2023-02-01,@pushpendrakum why we still listen to this Bul...,1620692173737046017,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,en,"<a href=""https://mobile.twitter.com"" rel=""nofo..."

In [27]:
df1['renderedContent']

0      @ysathishreddy @KTRBRS @prakashraaj @drgaganbh...
1      Where is Asia's richest person!\n#Adhani https...
2      Budget 2023 \n\nInda Budget mulamaa indiaya Po...
3      @SujathaGoud6 Telangana la mapia lu paripalana...
4      @pushpendrakum why we still listen to this Bul...
                             ...
995    Nimerelate na hiyi story ya Josh.Mamangu ashai...
996    புதிரா இந்தியா என்ற பெயரில் அதானி இந்தியா: 205...
997    @Macha_Icon Bro chunga asisahau akikupea bj ad...
998    @Siri4BRS Modhi desha drohi. Ramudu peru chepp...
999    Adhani Businesses \nalready in Eelam &amp; Sri...
Name: renderedContent, Length: 1000, dtype: object

***streamlit intallation***

In [28]:
!pip install -q streamlit

In [29]:
!pip install streamlit -q

In [9]:
!pip install pyngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pyngrok in /usr/local/lib/python3.8/dist-packages (5.2.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.8/dist-packages (from pyngrok) (6.0)

In [10]:
from pyngrok import ngrok

In [11]:
ngrok.set_auth_token('2KlmmvWjpNy6q1qda2ek5eg1VDC_5jWpKTVMqurQ6yA68PHEx')

In [12]:
!nohup streamlit run app.py --server.port 80 &

nohup: appending output to 'nohup.out'

In [13]:
ngrok.connect(port = '8080')

In [48]:
%%writefile app.py
#importing needed modules

import streamlit as st
import numpy as np
import pandas as pd
import datetime
import pandas as pd
import json
df1 = pd.read_json("/content/user-tweets.json",  lines=True)
df1['date'] = pd.to_datetime(df1['date']).dt.date
df1['time'] = pd.to_datetime(df1['date']).dt.time
df1['date']=df1['date'].astype(str)
df1['time']=df1['time'].astype(str)

#initiallizing mongodb connection
from pymongo import MongoClient
client=MongoClient("mongodb+srv://Alagammai:alagammai@cluster0.tgilzlf.mongodb.net/?retryWrites=true&w=majority")
db=client['twitterscrape']
my_col=db["adhani 1000 recent tweets"]
my_col.insert_many(df1.to_dict(orient='records'))

#creating dataframe and performing cleaning inside the app to be accessed in app
df = pd.read_json("/content/user-tweets.json",  lines=True)

df['date'] = pd.to_datetime(df['date']).dt.date
df['time'] = pd.to_datetime(df['date']).dt.time

@st.cache
# function to convert data to csv and json formats

def convert_df(df):
    return df.to_csv().encode('utf-8')
    return df.to_json().encode('utf-8')

df = df.drop(['_type','time', 'conversationId','sourceUrl','links','media','rawContent','quoteCount', 'inReplyToTweetId','inReplyToUser','mentionedUsers','coordinates', 'retweetedTweet', 'quotedTweet','sourceLabel','place',	'hashtags',	'cashtags',	'card','viewCount', 'vibe'], axis = 1)
# header for app
st.write("Twitter Scrapping")
#getting keywords, tweet count limit, date range from user

keyword = st.text_input('keyword or hastag to be searched', '')
tweetlimit = st.slider('maximum no of tweets', 0, 1000, 0)
start_date = st.date_input("select date range",datetime.date(2023, 1, 1))
end_date = st.date_input("select date range",datetime.date(2023, 2, 1))

# filterting data based on user input and displaying them 

df_filtered = df[df['renderedContent'].str.contains(keyword)]
df2 = df_filtered[df_filtered ['date'] >= start_date]
df3 = df2[df2['date'] <= end_date]
df4= df3.head(tweetlimit)
st.write("filtered data based on your input")
st.write(df4)

# converting datetime format to str as it will be needed for adding collection to mongodb database

df4['date']=df4['date'].astype(str)
data = df4.to_dict(orient = 'records')

#uploading data in database
#x = db.my_col.find({"$and" : [{'renderedContent' : {"$in" : [keyword]}}, {'date': {"$gte" : ISODate(start_date), "$lte" : ISODate(end_date)}}]}).limit(tweetlimit)
#y = data['id']
#db.my_col.find([y])
#x = db.my_col.find({"$and" : [{'renderedContent' : {"$in" : [keyword]}},{'date': {"$gte" : (start_date), "$lte" : (end_date)}}]}).limit(tweetlimit)
#for i in x:
  #print(i)
  #st.write(i)


if st.button('click here to upload'):
    convert = convert_df(df4)

    # creating download options for user

    st.download_button(
      label="Download data as CSV",
      data=convert,
      file_name='scraped data.csv',
      mime='text/csv',)
    st.download_button(label="Download data as json",data=convert,file_name='scraped data.json',mime='text/json')

Overwriting app.py