<a href="https://colab.research.google.com/github/Alagammaipl/twitter-data-scrapping/blob/main/Twitter_data_scraping_using_snscrape_and_streamlit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***installation of snscrape library***

In [1]:
!pip3 install snscrape

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting snscrape
  Downloading snscrape-0.5.0.20230113-py3-none-any.whl (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.2/69.2 KB 2.5 MB/s eta 0:00:00
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.8/dist-packages (from snscrape) (4.6.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.8/dist-packages (from snscrape) (3.9.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.8/dist-packages (from snscrape) (4.9.2)
Requirement already satisfied: pytz in /usr/local/lib/python3.8/dist-packages (from snscrape) (2022.7)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.8/dist-packages (from snscrape) (2.25.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (1.24.3)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (2022.12.7)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (1.7.1)
Installing collected packages: snscrape
Successfully installed snscrape-0.5.0.20230113

***scraping tweets***

In [2]:
!snscrape --jsonl --progress --max-results 1000 twitter-profile ElonMusk > user-tweets.json

Scraping, 100 results so far
Scraping, 200 results so far
Scraping, 300 results so far
Scraping, 400 results so far
Scraping, 500 results so far
Scraping, 600 results so far
Scraping, 700 results so far
Scraping, 800 results so far
Scraping, 900 results so far
Scraping, 1000 results so far
Stopped scraping after 1000 results due to --max-results

***converting to dataframe***

In [3]:
import pandas as pd
df = pd.read_json("/content/user-tweets.json",  lines=True)
df.head(5)

,_type,url,date,rawContent,renderedContent,id,user,replyCount,retweetCount,likeCount,...,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags,card,viewCount,vibe
0,snscrape.modules.twitter.Tweet,https://twitter.com/elonmusk/status/1616524886...,2023-01-20 19:55:41+00:00,Use pinned Lists to improve your Twitter exper...,Use pinned Lists to improve your Twitter exper...,1616524886201225217,"{'_type': 'snscrape.modules.twitter.User', 'us...",10637,9109,62306,...,NaN,None,None,NaN,NaN,None,NaN,None,10468972.0,NaN
1,snscrape.modules.twitter.Tweet,https://twitter.com/elonmusk/status/1618051634...,2023-01-25 01:02:26+00:00,@JudiciaryGOP @SpeakerMcCarthy This is important,@JudiciaryGOP @SpeakerMcCarthy This is important,1618051634734706688,"{'_type': 'snscrape.modules.twitter.User', 'us...",515,654,5824,...,1.618023e+18,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,None,NaN,None,412222.0,NaN
2,snscrape.modules.twitter.Tweet,https://twitter.com/elonmusk/status/1618029820...,2023-01-24 23:35:45+00:00,"RT @Tesla: Thank you to the Tesla team, our su...","RT @Tesla: Thank you to the Tesla team, our su...",1618029820553875456,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,727,0,...,NaN,None,"[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,None,NaN,None,1.0,NaN
3,snscrape.modules.twitter.Tweet,https://twitter.com/elonmusk/status/1618029785...,2023-01-24 23:35:37+00:00,RT @Tesla: We've come a long way since we brok...,RT @Tesla: We've come a long way since we brok...,1618029785376260096,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,636,0,...,NaN,None,"[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,None,NaN,None,1.0,NaN
4,snscrape.modules.twitter.Tweet,https://twitter.com/elonmusk/status/1618029749...,2023-01-24 23:35:28+00:00,"RT @Tesla: Today, we’re announcing $3.6B of ne...","RT @Tesla: Today, we’re announcing $3.6B of ne...",1618029749598851072,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,2463,0,...,NaN,None,"[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,None,NaN,None,2.0,NaN

**droping and modifications in df**

In [4]:
df['date'] = pd.to_datetime(df['date']).dt.date
df['time'] = pd.to_datetime(df['date']).dt.time
df

,_type,url,date,rawContent,renderedContent,id,user,replyCount,retweetCount,likeCount,...,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags,card,viewCount,vibe,time
0,snscrape.modules.twitter.Tweet,https://twitter.com/elonmusk/status/1616524886...,2023-01-20,Use pinned Lists to improve your Twitter exper...,Use pinned Lists to improve your Twitter exper...,1616524886201225217,"{'_type': 'snscrape.modules.twitter.User', 'us...",10637,9109,62306,...,None,None,NaN,NaN,None,NaN,None,10468972.0,NaN,00:00:00
1,snscrape.modules.twitter.Tweet,https://twitter.com/elonmusk/status/1618051634...,2023-01-25,@JudiciaryGOP @SpeakerMcCarthy This is important,@JudiciaryGOP @SpeakerMcCarthy This is important,1618051634734706688,"{'_type': 'snscrape.modules.twitter.User', 'us...",515,654,5824,...,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,None,NaN,None,412222.0,NaN,00:00:00
2,snscrape.modules.twitter.Tweet,https://twitter.com/elonmusk/status/1618029820...,2023-01-24,"RT @Tesla: Thank you to the Tesla team, our su...","RT @Tesla: Thank you to the Tesla team, our su...",1618029820553875456,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,727,0,...,None,"[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,None,NaN,None,1.0,NaN,00:00:00
3,snscrape.modules.twitter.Tweet,https://twitter.com/elonmusk/status/1618029785...,2023-01-24,RT @Tesla: We've come a long way since we brok...,RT @Tesla: We've come a long way since we brok...,1618029785376260096,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,636,0,...,None,"[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,None,NaN,None,1.0,NaN,00:00:00
4,snscrape.modules.twitter.Tweet,https://twitter.com/elonmusk/status/1618029749...,2023-01-24,"RT @Tesla: Today, we’re announcing $3.6B of ne...","RT @Tesla: Today, we’re announcing $3.6B of ne...",1618029749598851072,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,2463,0,...,None,"[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,None,NaN,None,2.0,NaN,00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,snscrape.modules.twitter.Tweet,https://twitter.com/elonmusk/status/1602943080...,2022-12-14,@naturalzzz @EMTSLA @jcn92977110 🎯,@naturalzzz @EMTSLA @jcn92977110 🎯,1602943080432295937,"{'_type': 'snscrape.modules.twitter.User', 'us...",74,110,1786,...,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,None,NaN,None,NaN,NaN,00:00:00
996,snscrape.modules.twitter.Tweet,https://twitter.com/elonmusk/status/1602919258...,2022-12-14,@BillyM2k @WholeMarsBlog Oh man that would be ...,@BillyM2k @WholeMarsBlog Oh man that would be ...,1602919258450583552,"{'_type': 'snscrape.modules.twitter.User', 'us...",969,1110,21550,...,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,None,NaN,None,NaN,NaN,00:00:00
997,snscrape.modules.twitter.Tweet,https://twitter.com/elonmusk/status/1602918922...,2022-12-14,@BillyM2k Yay!,@BillyM2k Yay!,1602918922193235968,"{'_type': 'snscrape.modules.twitter.User', 'us...",252,238,5848,...,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,None,NaN,None,NaN,NaN,00:00:00
998,snscrape.modules.twitter.Tweet,https://twitter.com/elonmusk/status/1602914925...,2022-12-14,@BillyM2k @Vvilelyn They just kept calling dif...,@BillyM2k @Vvilelyn They just kept calling dif...,1602914925273182208,"{'_type': 'snscrape.modules.twitter.User', 'us...",1584,4402,20276,...,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,None,NaN,None,NaN,NaN,00:00:00
999,snscrape.modules.twitter.Tweet,https://twitter.com/elonmusk/status/1602886199...,2022-12-14,@VitalikButerin https://t.co/PwnIrTf1Ej,@VitalikButerin https://t.co/PwnIrTf1Ej,1602886199181393920,"{'_type': 'snscrape.modules.twitter.User', 'us...",1527,1037,35505,...,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,None,NaN,None,NaN,NaN,00:00:00

In [5]:
df1 = df.drop(['_type','time', 'conversationId','sourceUrl','links','media','rawContent','quoteCount', 'inReplyToTweetId','inReplyToUser','mentionedUsers','coordinates', 'retweetedTweet', 'quotedTweet','sourceLabel','place',	'hashtags',	'cashtags',	'card','viewCount', 'vibe'], axis = 1)
df1.head()

,url,date,renderedContent,id,user,replyCount,retweetCount,likeCount,lang,source
0,https://twitter.com/elonmusk/status/1616524886...,2023-01-20,Use pinned Lists to improve your Twitter exper...,1616524886201225217,"{'_type': 'snscrape.modules.twitter.User', 'us...",10637,9109,62306,en,NaN
1,https://twitter.com/elonmusk/status/1618051634...,2023-01-25,@JudiciaryGOP @SpeakerMcCarthy This is important,1618051634734706688,"{'_type': 'snscrape.modules.twitter.User', 'us...",515,654,5824,en,NaN
2,https://twitter.com/elonmusk/status/1618029820...,2023-01-24,"RT @Tesla: Thank you to the Tesla team, our su...",1618029820553875456,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,727,0,en,NaN
3,https://twitter.com/elonmusk/status/1618029785...,2023-01-24,RT @Tesla: We've come a long way since we brok...,1618029785376260096,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,636,0,en,NaN
4,https://twitter.com/elonmusk/status/1618029749...,2023-01-24,"RT @Tesla: Today, we’re announcing $3.6B of ne...",1618029749598851072,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,2463,0,en,NaN

***streamlit intallation***

In [6]:
!pip install -q streamlit

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.3/9.3 MB 37.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.9/238.9 KB 26.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.8/164.8 KB 16.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.0/184.0 KB 22.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.0/79.0 KB 9.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 83.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 KB 7.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.5/84.5 KB 10.6 MB/s eta 0:00:00
  Building wheel for validators (setup.py) ... done

In [7]:
!pip install streamlit -q

In [8]:
!pip install pyngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyngrok
  Downloading pyngrok-5.2.1.tar.gz (761 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 761.3/761.3 KB 17.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: PyYAML in /usr/local/lib/python3.8/dist-packages (from pyngrok) (6.0)
Building wheels for collected packages: pyngrok
  Building wheel for pyngrok (setup.py) ... done
  Created wheel for pyngrok: filename=pyngrok-5.2.1-py3-none-any.whl size=19792 sha256=7032bf6689bfb2b74cc9f422278f6efbc18d9ab53518703380f25a0efe412654
  Stored in directory: /root/.cache/pip/wheels/5d/f2/70/526da675d32f17577ec47ac4c663084efe39d47c826b6c3bb1
Successfully built pyngrok
Installing collected packages: pyngrok
Successfully installed pyngrok-5.2.1

In [9]:
from pyngrok import ngrok

In [10]:
ngrok.set_auth_token('2KlmmvWjpNy6q1qda2ek5eg1VDC_5jWpKTVMqurQ6yA68PHEx')

In [12]:
!nohup streamlit run app.py --server.port 80 &

nohup: appending output to 'nohup.out'

In [13]:
ngrok.connect(port = '8080')

In [29]:
%%writefile app.py
#importing needed modules

import streamlit as st
import numpy as np
import pandas as pd
import datetime
import pandas as pd
from pymongo import MongoClient
import json

#initiallizing mongodb connection

client=MongoClient("mongodb+srv://Alagammai:alagammai@cluster0.tgilzlf.mongodb.net/?retryWrites=true&w=majority")
db=client['twitter_scrape']
# fuction to write data in database

@st.cache
def load_mongo_data(coll_name):
    data = db.coll_name.find()
    for documents in data:
        print(documents)
# function to convert data to csv and json formats

def convert_df(df):
    return df.to_csv().encode('utf-8')
    return df.to_json().encode('utf-8')
#creating dataframe and performing cleaning inside the app to be accessed in app

df = pd.read_json("/content/user-tweets.json",  lines=True)
df['date'] = pd.to_datetime(df['date']).dt.date
df['time'] = pd.to_datetime(df['date']).dt.time
df1 = df.drop(['_type','time', 'conversationId','sourceUrl','links','media','rawContent','quoteCount', 'inReplyToTweetId','inReplyToUser','mentionedUsers','coordinates', 'retweetedTweet', 'quotedTweet','sourceLabel','place',	'hashtags',	'cashtags',	'card','viewCount', 'vibe'], axis = 1)

#getting keywords, tweet cout limit, date range from user

keyword = st.text_input('keyword', 'key')
tweetlimit = st.slider('maximum no of times tweeted', 0, 258512, 100)
start_date = st.date_input("select date range",datetime.date(2023, 1, 1))
end_date = st.date_input("select date range",datetime.date(2023, 1, 24))

# filterting data based on user input and displaying them 

df_filtered = df1[df1['renderedContent'].str.contains(keyword)]
df2= df_filtered[df_filtered['retweetCount'] <= tweetlimit]
df3 = df2[df2['date'] >= start_date]
df4 = df3[df3['date'] <= end_date]
st.write(df4)

# converting datetime format to str as it will be needed for adding collection to mongodb database

df4['date']=df4['date'].astype(str)

#uploading data in database

if st.button('upload'):
    my_col=db["your data"]
    my_col.insert_many(df4.to_dict('records'))
    convert = convert_df(df4)

    # creating download options for user

    st.download_button(
      label="Download data as CSV",
      data=convert,
      file_name='yourdata.csv',
      mime='text/csv',)
    st.download_button(label="Download data as json",data=convert,file_name='yourdata.json',mime='text/json')

Overwriting app.py